name: UrlShortner

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Screens
      uses: actions/setup-go@v2
      with:
        go-version: 1.18

    - name: UrlShortner
      run: go build -v ./...

    - name: Testsc
      run: go test -v ./...
